name: CL
on:
  push:
    branches:
      - main
   
jobs:
  CL:
    runs-on: ubuntu-latest
    steps:
      - name: Check for IsJWT Secret
        id: IsJWT
        shell: bash
        run: |
          if [ "${{ secrets.IsJWT }}" != '' ]; then
            echo "available=true" >> $GITHUB_OUTPUT;
          else
            echo "available=false" >> $GITHUB_OUTPUT;
          fi

      - name: Set IsJWT Value
        if: ${{ steps.IsJWT.outputs.available == 'true' }}
        id: IsJWTValue
        shell: bash
        run: |
          if [ "${{ secrets.IsJWT }}" == 'false' ]; then
            echo "value=0" >> $GITHUB_OUTPUT;
          else
            echo "value=1" >> $GITHUB_OUTPUT;
          fi

      - uses: actions/checkout@v4
      - name: Run HoneygainPot (NEW)
        if: ${{ steps.IsJWT.outputs.available == 'true' }}
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }} # <- DO NOT enter your email here, it may leak your information
          PASS: ${{ secrets.PASS }} # <- DO NOT enter your password here, it may leak your information
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # <- DO NOT enter your JWT Token here, it may leak your information
          IsJWT: ${{ steps.IsJWTValue.outputs.value }} # DO NOT Touch THIS
      - uses: actions/checkout@v4
      - name: Run HoneygainPot (OLD)
        if: ${{ steps.IsJWT.outputs.available != 'true' }}
        run: python main.py
        env:
          MAIL: ${{ secrets.MAIL }} # <- DO NOT enter your email here, it may leak your information
          PASS: ${{ secrets.PASS }} # <- DO NOT enter your password here, it may leak your information
          JWT_TOKEN: ${{ secrets.JWT_TOKEN }} # <- DO NOT enter your JWT Token here, it may leak your information
          IsJWT: 1 # <- 0 = Use Mail and Pass ; 1 = Use Token (Default is 1)